import type { Metadata } from "next";
import { Lexend, Madimi_One } from "next/font/google";
import "./globals.css";

const lexend = Lexend({
  variable: "--font-lexend",
  subsets: ["latin"],
});

const madimiOne = Madimi_One({
  variable: "--font-madimi",
  subsets: ["latin"],
  weight: "400",
  style: "normal",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${lexend.variable} ${madimiOne.variable} antialiased`}>
        {children}
      </body>
    </html>
  );
}
